spring:
  kafka:
    properties:
      schema:
        registry:
          url: http://localhost:28081/
  cloud:
    stream:
      # Configuração para todos os producers
      default:
        producer:
          use-native-encoding: true
      bindings:
        producer-out-0:
          destination: xpto
          # Configuração individual por binding
      #          producer:
      #            use-native-encoding: false
      kafka:
        binder:
          brokers:
            - localhost:29093
          configuration:
            security:
              protocol: SSL
            ssl:
              endpoint:
                identification:
                  algorithm: ""
              truststore:
                location: classpath:/ssl/localhost.truststore.pkcs12
                password: test1234
                type: PKCS12
              keystore:
                location: classpath:/ssl/localhost.keystore.pkcs12
                password: test1234
                type: PKCS12
              key:
                password: test1234
              keymanager:
                algorithm: PKIX
              trustmanager:
                algorithm: PKIX
              enabled:
                protocols: TLSv1.3,TLSv1.3
        #Configuração individual por Binding
        #        bindings:
        #          producer-out-0:
        #            producer:
        #              configuration:
        #                key:
        #                  serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        #                  deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        #                value:
        #                  serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        #                  deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        # Configuração para todos os producers
        default:
          producer:
            configuration:
              key:
                serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
              value:
                serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

