spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - kafka:9093
  kafka:
    properties:
      schema:
        registry:
          url: http://schema-registry:8081

